[book]
title = "Arcadia Documentation"
author = "?"
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "dark"
git-repository-url = "https://github.com/Arcadia-Solutions/arcadia"
